<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Listing\Listing;

class ListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Listing::create([
            'id' => '1',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1626967267335_74455.pdf',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1626967342600_92369.png',
            'car_plate_number' => 'BC000',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": null, "dashboard": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627696711434_12297.JPG", "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627696701221_30790.JPG", "front_left": null, "front_view": null, "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627696695234_58734.JPG", "speedometer": null, "interior_back": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627696704777_10880.JPG", "interior_front": null, "left_side_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627696698457_55118.JPG", "right_side_view": null}',
            'car_body_type' => 'SEDAN 4DR',
            'car_make_name' => 'AUDI',
            'mileage' => '20000',
            'model' => '80',
            'manufacture_year' => '2020',
            'transmission' => 'auto',
            'fuel_type' => 'PETROL',
            'doors' => '5',
            'engine_size' => '1300',
            'color' => 'White',
            'listing_type' => 'auction',
            'ad_title' => 'This is listing ad',
            'ad_description' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            'state' => 'Kuala Lumpur',
            'area' => 'Bangsar South',
            'variant' => NULL,
            'asking_price' => NULL,
            'starting_price' => '20000',
            'reserve_price' => '34000',
            'buy_now_price' => '34000',
            'duration_of_auction' => '7',
            'start_date' => '2021-07-22 15:25:20',
            'end_date' => '2021-07-29 15:25:20',
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'highlight_end_date' => NULL,
            'is_feature' => '1',
            'feature_end_date' => '2021-08-23 14:25:39',
            'user_id' => '2',
            'created_at' => '2021-07-22 15:25:20',
            'updated_at' => '2021-07-23 14:25:39',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '2',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636953923_96475.jfif',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636914490_13328.jpg',
            'car_plate_number' => 'ty476',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": null, "dashboard": null, "back_right": null, "front_left": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636967154_77849.jpg", "front_view": null, "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636969446_47679.jpg", "speedometer": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636977313_20882.jpg", "interior_back": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636990901_18864.jpg", "interior_front": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636982929_66031.jpg", "left_side_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627636971964_29457.jpg", "right_side_view": null}',
            'car_body_type' => 'SEDAN',
            'car_make_name' => 'MERCEDES-BENZ',
            'mileage' => '73000',
            'model' => 'S-CLASS',
            'manufacture_year' => '2013',
            'transmission' => 'auto',
            'fuel_type' => 'PETROL',
            'doors' => '5',
            'engine_size' => '2982',
            'color' => 'Black',
            'listing_type' => 'auction',
            'ad_title' => '2013 Mercedes-Benz S300 100th Aniversary edition',
            'ad_description' => 'Mercedes Benz S300 L (CKD) 3.0 FACELIFT MAYBACH\n\n*** LOCAL SPEC*** 3.0 L V6 LONG WHEEL BASE LIMOUSINE\n*** DIRECTOR CAREFUL OWNER\n*** NICE VIP NUMBER PLATE\n*** LEATHER SEAT\n*** ELECTRIC SEAT\n*** GPS NAVIGATION SYSTEM\n*** POWER BOOT\n*** SUNROOF\n*** MULTI FUNCTION POWER STEERING\n*** AUTO CRUISE CONTROL\n*** BI-XENON LIGHT\n*** REVERSE SENSOR (PARKTRONIC)\n*** VACUUM DOORS\n*** AIRBAG\n*** ANTI BRAKE SYSTEM (ABS)\n*** RADIO & CD PLAYER\n*** 231 BHP HORSE POWER\n*** 7 SPEED GEARBOX\n*** 20\" SPORT RIMS\n*** MAYBACH STYLE\n*** PRICE NEGOTIABLE\n*** EXCELLENT CONDITION\n*** WELL MAINTAINED\n*** LOW MILAGE\n*** 100% ACCIDENT FREE\n*** READY STOCK\n*** ACCEPT TRADE IN\n*** MANY EXTRAS\n*** GOOD RUNNING CONDITION\n*** WELL MAINTENANCE\n*** WELL KEPT\n*** TIP TOP CONDITION\n*** MUST VIEW YOUR DREAM CAR\n\n@@@ SELLING CAR PRICE RM49,800.00 @@@\n\n!!! CALL NOW TO GET YOUR DREAM CAR !!!\n\nPLEASE COME VISIT OUR SHOWROOM :\n\n@@@ CASH BUYER ARE WELCOME @@@',
            'state' => 'Kuala Lumpur',
            'area' => 'Bangsar',
            'variant' => 'S 300 TURBO-D (140.135) (177 HP)',
            'asking_price' => NULL,
            'starting_price' => '12000',
            'reserve_price' => '40000',
            'buy_now_price' => '58000',
            'duration_of_auction' => '7',
            'start_date' => '2021-07-30 17:30:08',
            'end_date' => '2021-08-06 17:30:08',
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '1',
            'highlight_end_date' => '2021-08-23 14:25:39',
            'is_feature' => '0',
            'feature_end_date' => NULL,
            'user_id' => '4',
            'created_at' => '2021-07-30 17:30:08',
            'updated_at' => '2021-07-30 17:30:08',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '3',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699582454_70363.jfif',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699541629_36900.JPG',
            'car_plate_number' => 'S1',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699560204_23372.JPG", "dashboard": null, "back_right": null, "front_left": null, "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699556886_17416.JPG", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699553415_13212.JPG", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699563707_71894.JPG", "right_side_view": null}',
            'car_body_type' => 'CONVERTIBLE',
            'car_make_name' => 'FERRARI',
            'mileage' => '18008',
            'model' => 'F430',
            'manufacture_year' => '2007',
            'transmission' => 'auto',
            'fuel_type' => 'PETROL',
            'doors' => '2',
            'engine_size' => '3586',
            'color' => 'Red',
            'listing_type' => 'auction',
            'ad_title' => '2007 Ferrari F430 Spider',
            'ad_description' => '••••••••••••••••••••••••••••••••••••••••••••••\n*1 VIP OWNER\n*LOW MILEAGE & WELL MAINTAINED BY OWNER\n*PININFARINA AERODYNAMIC DESIGN\n*4.3L V8 ENGINE\n*490 HP. TOP SPEED 315 km/h. 0-100 km/h 3.6 SECONDS.\n*6 SPEED F1 AUTOMATIC TRANSMISSION\n*FULL EXHAUST SYSTEM BY KREISSIEG\n*REAR WHEEL DRIVE\n*CARBON FIBRE SKIRTING & SIDE MIRRORS\n*CREMA ELECTRICAL NAPA LEATHER doors\n*SPORTS LEATHER STEERING WITH PADDLE SHIFT\n*CARBON CERAMIC BRAKES\n*19” ALLOY RIMS WITH MICHELIN PILOT SPORT TYRES\n*16 CHANNEL RADIO WITH DOLBY SURROUND SOUND SPEAKERS\n*DUAL ZONE AUTOMATIC AIR COND',
            'state' => 'Kuala Lumpur',
            'area' => 'Bangsar',
            'variant' => '360 SPIDER (400 HP)',
            'asking_price' => NULL,
            'starting_price' => '88000',
            'reserve_price' => '280000',
            'buy_now_price' => '380000',
            'duration_of_auction' => '7',
            'start_date' => '2021-07-31 10:52:52',
            'end_date' => '2021-08-07 10:52:52',
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '3',
            'created_at' => '2021-07-31 10:52:52',
            'updated_at' => '2021-07-31 10:52:52',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '4',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489460569_69726.png',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489421128_84631.jpg',
            'car_plate_number' => '177',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489567839_77793.jpg", "back_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489571595_11360.jpg", "dashboard": null, "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489564448_14560.jpg", "front_left": null, "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489561860_69287.jpg", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627489557768_45220.jpg", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": null, "right_side_view": null}',
            'car_body_type' => 'COUPE',
            'car_make_name' => 'TOYOTA',
            'mileage' => '40000',
            'model' => '86',
            'manufacture_year' => '2013',
            'transmission' => 'auto',
            'fuel_type' => 'PETROL',
            'doors' => '2',
            'engine_size' => '1998',
            'color' => 'Blue',
            'listing_type' => 'classified',
            'ad_title' => 'Toyota FT86 Super blue',
            'ad_description' => 'AE 86 brother',
            'state' => 'Kuala Lumpur',
            'area' => 'Setia Eco Park',
            'variant' => '2.0 D-4S (200 HP) AUTOMATIC',
            'asking_price' => '150000',
            'starting_price' => NULL,
            'reserve_price' => NULL,
            'buy_now_price' => NULL,
            'duration_of_auction' => NULL,
            'start_date' => NULL,
            'end_date' => NULL,
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '2',
            'created_at' => '2021-07-29 00:28:16',
            'updated_at' => '2021-07-29 00:28:16',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '5',
            'car_condition' => 'new',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627363244124_73949.pdf',
            'car_plate_verification_image' => NULL,
            'car_plate_number' => NULL,
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": null, "dashboard": null, "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627363252685_80558.jpg", "front_left": null, "front_view": null, "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627363250224_47468.jpg", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": null, "right_side_view": null}',
            'car_body_type' => 'SUV',
            'car_make_name' => 'PERODUA',
            'mileage' => '0',
            'model' => 'ATIVA',
            'manufacture_year' => '2021',
            'transmission' => 'auto',
            'fuel_type' => 'PETROL',
            'doors' => '5',
            'engine_size' => '1000',
            'color' => 'Red',
            'listing_type' => 'classified',
            'ad_title' => 'All New Perodua Ativa 1.0 Turbo',
            'ad_description' => NULL,
            'state' => 'Kuala Lumpur',
            'area' => 'Kepong',
            'variant' => NULL,
            'asking_price' => '68888',
            'starting_price' => NULL,
            'reserve_price' => NULL,
            'buy_now_price' => NULL,
            'duration_of_auction' => NULL,
            'start_date' => NULL,
            'end_date' => NULL,
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '2',
            'created_at' => '2021-07-27 13:22:15',
            'updated_at' => '2021-07-27 13:22:15',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '6',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437514071_84925.pdf',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437407672_24878.jpeg',
            'car_plate_number' => 'SKY100',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": null, "dashboard": null, "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437549234_72128.jpeg", "front_left": null, "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437546337_18116.jpeg", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437539952_86119.jpeg", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": null, "right_side_view": null}',
            'car_body_type' => 'MPV',
            'car_make_name' => 'KIA',
            'mileage' => '34000',
            'model' => 'CARNIVAL',
            'manufacture_year' => '2018',
            'transmission' => 'auto',
            'fuel_type' => 'DIESEL',
            'doors' => '8',
            'engine_size' => '2200',
            'color' => 'Black',
            'listing_type' => 'classified',
            'ad_title' => 'KIA CARNIVAL 2018 NEW MODEL',
            'ad_description' => NULL,
            'state' => 'Kuala Lumpur',
            'area' => 'KL City',
            'variant' => NULL,
            'asking_price' => '102000',
            'starting_price' => NULL,
            'reserve_price' => NULL,
            'buy_now_price' => NULL,
            'duration_of_auction' => NULL,
            'start_date' => NULL,
            'end_date' => NULL,
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '2',
            'created_at' => '2021-07-28 10:02:03',
            'updated_at' => '2021-07-28 10:02:03',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '7',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437514071_84925.pdf',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437407672_24878.jpeg',
            'car_plate_number' => 'SKY100',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": null, "dashboard": null, "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437549234_72128.jpeg", "front_left": null, "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437546337_18116.jpeg", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437539952_86119.jpeg", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": null, "right_side_view": null}',
            'car_body_type' => 'MPV',
            'car_make_name' => 'KIA',
            'mileage' => '34000',
            'model' => 'CARNIVAL',
            'manufacture_year' => '2018',
            'transmission' => 'auto',
            'fuel_type' => 'DIESEL',
            'doors' => '8',
            'engine_size' => '2200',
            'color' => 'Black',
            'listing_type' => 'classified',
            'ad_title' => 'KIA CARNIVAL 2018 NEW MODEL',
            'ad_description' => NULL,
            'state' => 'Kuala Lumpur',
            'area' => 'KL City',
            'variant' => NULL,
            'asking_price' => '102000',
            'starting_price' => NULL,
            'reserve_price' => NULL,
            'buy_now_price' => NULL,
            'duration_of_auction' => NULL,
            'start_date' => NULL,
            'end_date' => NULL,
            'listing_status' => 'pending_approval',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '2',
            'created_at' => '2021-07-28 10:02:03',
            'updated_at' => '2021-07-28 10:02:03',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '8',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437514071_84925.pdf',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437407672_24878.jpeg',
            'car_plate_number' => 'SKY100',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": null, "dashboard": null, "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437549234_72128.jpeg", "front_left": null, "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437546337_18116.jpeg", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627437539952_86119.jpeg", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": null, "right_side_view": null}',
            'car_body_type' => 'MPV',
            'car_make_name' => 'KIA',
            'mileage' => '34000',
            'model' => 'CARNIVAL',
            'manufacture_year' => '2018',
            'transmission' => 'auto',
            'fuel_type' => 'DIESEL',
            'doors' => '8',
            'engine_size' => '2200',
            'color' => 'Black',
            'listing_type' => 'classified',
            'ad_title' => 'KIA CARNIVAL 2018 NEW MODEL',
            'ad_description' => NULL,
            'state' => 'Kuala Lumpur',
            'area' => 'KL City',
            'variant' => NULL,
            'asking_price' => '102000',
            'starting_price' => NULL,
            'reserve_price' => NULL,
            'buy_now_price' => NULL,
            'duration_of_auction' => NULL,
            'start_date' => NULL,
            'end_date' => NULL,
            'listing_status' => 'sold',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '2',
            'created_at' => '2021-07-28 10:02:03',
            'updated_at' => '2021-07-28 10:02:03',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '9',
            'car_condition' => 'used',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699582454_70363.jfif',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699541629_36900.JPG',
            'car_plate_number' => 'S1',
            'car_images' => '{"gear": null, "engine": null, "other_1": null, "other_2": null, "rim_tire": null, "back_left": null, "back_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699560204_23372.JPG", "dashboard": null, "back_right": null, "front_left": null, "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699556886_17416.JPG", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699553415_13212.JPG", "speedometer": null, "interior_back": null, "interior_front": null, "left_side_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627699563707_71894.JPG", "right_side_view": null}',
            'car_body_type' => 'CONVERTIBLE',
            'car_make_name' => 'FERRARI',
            'mileage' => '18008',
            'model' => 'F430',
            'manufacture_year' => '2007',
            'transmission' => 'auto',
            'fuel_type' => 'PETROL',
            'doors' => '2',
            'engine_size' => '3586',
            'color' => 'Red',
            'listing_type' => 'auction',
            'ad_title' => '2007 Ferrari F430 Spider',
            'ad_description' => '••••••••••••••••••••••••••••••••••••••••••••••\n*1 VIP OWNER\n*LOW MILEAGE & WELL MAINTAINED BY OWNER\n*PININFARINA AERODYNAMIC DESIGN\n*4.3L V8 ENGINE\n*490 HP. TOP SPEED 315 km/h. 0-100 km/h 3.6 SECONDS.\n*6 SPEED F1 AUTOMATIC TRANSMISSION\n*FULL EXHAUST SYSTEM BY KREISSIEG\n*REAR WHEEL DRIVE\n*CARBON FIBRE SKIRTING & SIDE MIRRORS\n*CREMA ELECTRICAL NAPA LEATHER doors\n*SPORTS LEATHER STEERING WITH PADDLE SHIFT\n*CARBON CERAMIC BRAKES\n*19” ALLOY RIMS WITH MICHELIN PILOT SPORT TYRES\n*16 CHANNEL RADIO WITH DOLBY SURROUND SOUND SPEAKERS\n*DUAL ZONE AUTOMATIC AIR COND',
            'state' => 'Kuala Lumpur',
            'area' => 'Bangsar',
            'variant' => '360 SPIDER (400 HP)',
            'asking_price' => NULL,
            'starting_price' => '88000',
            'reserve_price' => '280000',
            'buy_now_price' => '380000',
            'duration_of_auction' => '7',
            'start_date' => '2021-07-31 10:52:52',
            'end_date' => '2021-08-07 10:52:52',
            'listing_status' => 'expired',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '2',
            'created_at' => '2021-07-31 10:52:52',
            'updated_at' => '2021-07-31 10:52:52',
            'categories_id' => '1'
        ]);

        Listing::create([
            'id' => '10',
            'car_condition' => 'recon',
            'car_ownership_document' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098016079_45581.pdf',
            'car_plate_verification_image' => 'https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098001021_16382.jpg',
            'car_plate_number' => 'QAV6383',
            'car_images' => '{"gear": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098089393_33298.jpg", "engine": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098059840_24504.jpg", "other_1": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098101424_73587.jpg", "other_2": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098104938_75495.jpg", "rim_tire": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098097831_78793.jpg", "back_left": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098036428_72328.jpg", "back_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098040089_51355.jpg", "dashboard": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098067835_55442.jpg", "back_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098032875_96901.jpg", "front_left": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098043638_89243.png", "front_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098028432_57356.jpg", "front_right": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098023484_61882.jpg", "speedometer": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098092929_27980.jpg", "interior_back": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098077608_24036.jpg", "interior_front": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098082326_69113.jpg", "left_side_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098048012_37908.jpg", "right_side_view": "https://byparts-spaces.sgp1.digitaloceanspaces.com/byparts-spaces/market-place/1627098055343_12185.jpg"}',
            'car_body_type' => 'QAV',
            'car_make_name' => 'BENTLEY',
            'mileage' => '6000',
            'model' => 'BENTAYGA',
            'manufacture_year' => '1980',
            'transmission' => 'manual',
            'fuel_type' => 'PETROL',
            'doors' => '6',
            'engine_size' => '6800',
            'color' => 'Blue',
            'listing_type' => 'auction',
            'ad_title' => 'VOLVO + 8 YEARS WARRANTY',
            'ad_description' => 'Volvo Cars (Swedish: Volvo personvagnar), stylized as VOLVO, is a Swedish luxury automobile marque. It is headquartered in Torslanda in Gothenburg, Sweden. The company manufactures and markets sport utility vehicles (SUVs), station wagons, hatchbacks, sedans and compact executive sedans.',
            'state' => 'Terengganu',
            'area' => 'Kuala Terengganu',
            'variant' => NULL,
            'asking_price' => '21500000',
            'starting_price' => '30000',
            'reserve_price' => '80000',
            'buy_now_price' => '60000',
            'duration_of_auction' => '8',
            'start_date' => '2021-07-24 03:44:35',
            'end_date' => '2021-08-24 03:44:35',
            'listing_status' => 'published',
            'rejection_reason' => NULL,
            'is_highlight' => '0',
            'user_id' => '3',
            'created_at' => '2021-07-24 03:44:35',
            'updated_at' => '2021-07-24 03:44:35',
            'categories_id' => '1'
        ]);
    }
}
